name: grocery
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^7.0.0
  grouped_buttons: ^1.0.4
  carousel_slider: ^3.0.0
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.2
  flutter_local_notifications: ^6.0.0
  firebase_messaging: ^10.0.2
  shared_preferences: ^2.0.5
  toast: ^0.1.5
  http: ^0.13.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.1
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  image_picker: ^0.8.0+3
  shimmer_animation: ^2.0.0
  flutter_html: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  google_maps_flutter: ^2.0.2
  flutter_google_places: ^0.3.0
  #  google_place: ^0.4.0
  #  google_maps_webservice: ^0.0.19
  google_place: ^0.4.0
  mapbox_search: ^2.1.0+1
  #  horizontal_calendar_widget: ^1.0.2
  http_auth: ^1.0.0
  flutter_paystack: ^1.0.5
#  stripe_payment: ^1.1.1
#  flutter_stripe: ^1.0.2
  flutter_credit_card: ^2.0.0
  marquee: ^2.0.0
  pdf: ^3.1.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^2.0.1
  printing: ^5.0.4
  flutter_share: ^2.0.0
  badges: ^2.0.1
  flutter_speed_dial: ^3.0.5
  url_launcher: ^6.0.3
#  flutter_launch: ^0.2.0
  flat_segmented_control: ^0.1.0
  tree_view: ^0.0.5
  razorpay_flutter: ^1.2.6
  convex_bottom_bar: ^3.0.0
  awesome_notifications: 0.0.6+9
#  awesome_notifications: ^0.0.6+7


  intl_phone_number_input: ^0.7.0+2

  smooth_page_indicator: ^0.2.1
  dotted_border: ^2.0.0

  modal_bottom_sheet: ^2.0.0
  flutter_switch: ^0.3.1
  rflutter_alert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  json_serializable: ^3.4.1
  #  intl_translation: ^0.17.9
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
    - family: SF pro
      fonts:
        - asset: fonts/SFProText-Regular.ttf
    - family: SF bold
      fonts:
        - asset: fonts/SFProDisplay-Bold.ttf
    - family: SF semibold
      fonts:
        - asset: fonts/SFProDisplay-Semibold.ttf
    - family: aeh
      fonts:
        - asset: fonts/AEH.ttf
    - family: aer
      fonts:
        - asset: fonts/AER.ttf
    - family: Customicon
      fonts:
        - asset: fonts/Customicon.ttf


  assets:
    - assets/
    - assets/ProductImages/
    - assets/PaymentIcons/
    - assets/CategoryImages/
    - assets/HomeBanner/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf