/// Flutter icons Customicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicon
///      fonts:
///       - asset: fonts/Customicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Customicon {
  Customicon._();

  static const _kFontFam = 'Customicon';
  static const String _kFontPkg = null;

  static const IconData add_cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terms = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
